{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "simple-web-chart.fullname" . }}
spec:
  scaleTargetRef:
    name: {{ include "simple-web-chart.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
  - type: cpu
    metadata:     
        type: Utilization   
        value: "{{ .Values.keda.cpuTargetPercentage }}"        
  - type: memory
    metadata:   
        type: Utilization    
        value: "{{ .Values.keda.memTargetPercentage }}"
  - type: cron
    metadata:
      timezone: Asia/Kolkata
      start: 0 8 * * *
      end: 0 0 * * *
      desiredReplicas: "5"
{{- end -}}      
